### ISSUE TITLE
MaterialTextBox2 issue on initialization

### ISSUE THREAD

**Issue by valimaties** [leocb/MaterialSkin#238] opened 2021-10-13 05:52 UTC
( Copied from #227 )

Hi @VolatilePulse .
I downloaded your branch (aero-snapping) and tried in my project. Form size it will remains as it has been set before open it. That is very good.
But another problem it is happening with MaterialTextBox2 control in this branch. It doesn't loose focus (all textboxes has that colored focus bar in the bottom of control), only on initialization of form. Also, when I close a modal form, all textboxes will change its backcolor but only on text area. Pictures below:

![MTB1](https://user-images.githubusercontent.com/49796453/136940492-c4c1c414-7cfc-4462-8424-5db514bdb614.png)

![MTB2](https://user-images.githubusercontent.com/49796453/136940536-5914a011-6abc-47c2-b012-584e29e264f1.png)

This is a video showing the behavior:

https://user-images.githubusercontent.com/49796453/136949109-886f0c90-e8f3-41f3-a6ee-83fda6b2f1a6.mp4

**Comment by valimaties** [comment] 2021-10-14 06:21
I made a small project. I found that focus bar problem does not happens in this project, but background did. You have the solution in attached zip file. 
In gif file I also show a small problem with cursor when mouse over. It changes to IBeam only when the mouse is over the text area, not over the all control, which must be the default cursor of the entire object.

![StrangeBehavior](https://user-images.githubusercontent.com/49796453/137262199-a0f2497e-6d47-42f7-9f3d-ab9dea3026e7.gif)

[Test.zip](https://github.com/leocb/MaterialSkin/files/7343485/Test.zip)

**Comment by valimaties** [comment] 2021-10-14 08:55
The problem with focused textboxes is starting from design... I think it is an isolated case, so this issue can be solved in the future, if you can find the problem, if you can reproduce it. 
In example bellow, all textbox controls are custom MaterialTextBox2, named MyMaterialTextBox. And as you can see, a new instance  of those focused controls are created with focused effect. So, I think there must be made something in object constructor to invalidate object even in designer mode.

![StrangeBehavior2](https://user-images.githubusercontent.com/49796453/137284113-f746377c-81dc-4950-b763-c6a280be4b0d.gif)

**Comment by VolatilePulse** [comment] 2021-10-15 20:25
I'm sorry, I believe I may not have expressed myself clearly and that is my fault. It's difficult to track down the specific issue if we cannot emulate the issue. I asked if it worked in a fresh Windows 10 installation not because I feel the software should only work under that scenario, but so we can begin to narrow down specifically what causes the issues that you're experiencing.

I was hoping the issue that you were experiencing wouldn't be present on a VM because that would help us rule out a GPU and system files. Since you are encountering that issue in a VM, it is likely to be way above me and it won't be able to be fixed by myself.

Also, your screenshot you sent recently isn't showing the OnFocus issue you initially mentioned, or at least what I understand this issue to be about (the text boxes having focus, or the highlighted bar, when they shouldn't). I can see the outlined shape that you're talking about, the baseTextBox effectively showing through the MaterialTextBox, but I don't know what's causing it.

The reason it is important for developers to reproduce issues is so they can identify and fix the issue instead of just throwing code at an issue, possibly breaking something else. If you do know what the exact issue is and what needs to be fixed, I'm sure Orapps would gladly accept your PR or implement the specific change. But if you aren't sure what's causing it, it is important for us to reproduce the issue to attempt to fix it.

And please don't think that "can't reproduce" is a solution or a cop out. I wouldn't be asking you to test more things if I didn't genuinely want to help fix this issue. I feel that everyone should be able to enjoy MaterialSkin equally, regardless of what software is on their computer or what operating system they're working with, or what .NET version they're using. My material-form-refactor is specifically aiming to remove custom code and passing as much of the heavy lifting for the application onto Windows as possible. This allows for generally more consistent and big free experiences while also typically being faster.

**Comment by VolatilePulse** [comment] 2021-10-16 00:19
I've narrowed down the issue to the MaterialSkinManager's UpdateBackgrounds() method. That's what is causing the BaseTextBox to effectively inherit the form's background color. I'm not 100% why it's doing it and I'm not sure what the right approach is, but figured I'd leave my findings thus far.

**Comment by valimaties** [comment] 2021-10-16 05:24
Yes, @VolatilePulse , exactly ... I said about it right here https://github.com/leocb/MaterialSkin/issues/238#issuecomment-944239239
I was wandering myself why BaseTextBox must have a background color, instead of transparent background color. This control doesn't need a background color.

**Comment by orapps44** [comment] 2021-10-16 08:07
Hi,

I've found the root cause of focused control at startup (it occurs only if readonly property is set).
I will create a PR soon for that.

**Comment by orapps44** [comment] 2021-10-16 12:30
See PR #242

**Comment by valimaties** [comment] 2021-10-18 05:34
Thanks @orapps44 . Now it remains the background color for baseTextBox object.

**Comment by orapps44** [comment] 2021-10-31 00:06
Hi,

I've finnaly found a fix for background issue.
I still not fully understand issue root cause, however following update works for me.
Could you try it and le me know ?

See : https://github.com/leocb/MaterialSkin/tree/orapps44-MaterialTextBox2-backcolor-fix

**Comment by valimaties** [comment] 2021-10-31 14:41
> Hi,
> 
> I've finnaly found a fix for background issue. I still not fully understand issue root cause, however following update works for me. Could you try it and le me know ?
> 
> See : https://github.com/leocb/MaterialSkin/tree/orapps44-MaterialTextBox2-backcolor-fix

Hi @orapps44 ,
This seems to work fine on me, too. But with one other small problem: it will create a flickering view on divider (for example, in my case). So I've modified `Redraw` event and added `SuspendLayout` and `ResumeLayout` events, which eliminate flickering to objects, like this: 

![unflickering](https://user-images.githubusercontent.com/49796453/139588850-59bf593c-6651-4c10-974a-846f286a68d1.jpg)

**Closed** 2021-11-01 18:51 UTC
Labels: Visual
