### ISSUE TITLE
Toggling MaterialTextBox2's Enabled Property Doesn't Propagate to the Inner Control

### ISSUE THREAD

**Issue by VolatilePulse** [leocb/MaterialSkin#289] opened 2021-11-10 00:42 UTC
One of the scenarios at work is using a switch to toggle between using a local DB or server DB. If switching to a server DB, the user is required to provide a connection string which set's the text box's enable state to true. The outer control can receive focus, but the inner text box is still disabled.

Starting Disabled State with a Text value:
![image](https://user-images.githubusercontent.com/6995232/141028437-997e26c3-3ac4-4866-b148-ec7d24b0b613.png)

Toggled Enabled State with a Text Value:
![image](https://user-images.githubusercontent.com/6995232/141028467-0297e842-e256-4ed3-8673-6d4322c03854.png)

If the control starts enabled, everything works as expected at first. Once the Enabled state is toggled to false, you get the first image. Toggling the Enabled state to true again will get you the second image.

**Comment by valimaties** [comment] 2021-11-10 11:37
Sorry @VolatilePulse , I have tried your scenario and mine works as expected.
Did you inherit MaterialTextBox2 in a new class? 
Do you have some extra code inside that class to check for textbox's value? Maybe there is a problem...

Demo: starting disabled, switched to enabled and everything works fine...
![MaterialTextbox2EnabledChangeIssue](https://user-images.githubusercontent.com/49796453/141106306-97683121-4846-44fd-9006-71e854da372c.gif)

**Comment by orapps44** [comment] 2021-11-10 12:11
I can't reproduce that also.
Could you make a test project and share it ?

**Comment by VolatilePulse** [comment] 2021-11-10 13:47
This shows two issues, the inner control stays disabled while the outer control is enabled and the Hint text is overlapped by the Text value.

```cs
using MaterialSkin.Controls;
using System;
using System.Windows.Forms;

namespace WinFormsApp1
{
    internal static class Program
    {
        [STAThread]
        private static void Main()
        {
            Application.SetHighDpiMode(HighDpiMode.SystemAware);
            Application.EnableVisualStyles();
            Application.SetCompatibleTextRenderingDefault(false);
            Application.Run(new ExampleForm("Sample Text"));
        }
    }

    public partial class ExampleForm : MaterialForm
    {
        public ExampleForm(string textBoxString)
        {
            InitializeComponent();
            ExampleTextBox.Text = textBoxString;
        }

        public MaterialTextBox2 ExampleTextBox = new();
        public MaterialSwitch ExampleSwitch = new();

        private void InitializeComponent()
        {
            ClientSize = new System.Drawing.Size(800, 450);
            Text = "Example Form";

            ExampleTextBox.Hint = "Test";
            ExampleTextBox.Text = string.Empty;
            ExampleTextBox.Enabled = false;
            ExampleTextBox.Location = new System.Drawing.Point(32, 100);
            ExampleTextBox.Size = new System.Drawing.Size(200, 60);

            ExampleSwitch.Text = "TextBox Enabled";
            ExampleSwitch.Location = new System.Drawing.Point(264, 100);
            ExampleSwitch.Size = new System.Drawing.Size(200, 20);
            ExampleSwitch.Click += ExampleSwitch_Click;

            Controls.Add(ExampleTextBox);
            Controls.Add(ExampleSwitch);
        }

        private void ExampleSwitch_Click(object? sender, EventArgs e) => ExampleTextBox.Enabled = ExampleSwitch.Checked;
    }
}
```

**Comment by valimaties** [comment] 2021-11-10 22:00
Hi @VolatilePulse ,
I've tried your code and works fine for me for Enabled issue. Yes, there is a problem with baseTextBox position when Hint is visible and not empty.

Demo:
![VolatileIssue](https://user-images.githubusercontent.com/49796453/141200409-13069998-c262-4a75-84f0-655344909a8e.gif)

**Comment by valimaties** [comment] 2021-11-10 22:26
Hi @VolatilePulse 
Try my PR #292 and see if it solve your problem.

Demo:
![VolatileIssue_PRSolve](https://user-images.githubusercontent.com/49796453/141203805-c9f00429-c86b-42d9-b1f1-d51a3750930f.gif)

**Comment by orapps44** [comment] 2021-11-11 13:03
Overlapping fix has been merged into master.
Could you try again and tell us if everything is fixed ?

**Comment by VolatilePulse** [comment] 2021-11-11 14:43
Part of the confusion was because I was using an older commit. I misunderstood the usage of `git submodule`. After pulling the latest version, all issues have been resolved. Thank you.

**Closed** 2021-11-11 14:43 UTC
