### ISSUE TITLE
Combobox Appears as Black Box on Designer

### ISSUE THREAD

**Issue by seikosantana** [leocb/MaterialSkin#167] opened 2021-04-23 02:38 UTC
As the title says, it happens only on designer.
![image](https://user-images.githubusercontent.com/35630407/115810238-d3d3ac80-a417-11eb-89da-3aa6aadad97a.png)

**Comment by seikosantana** [comment] 2021-04-23 02:39
As the title says, it happens only on designer.
![image](https://user-images.githubusercontent.com/35630407/115810238-d3d3ac80-a417-11eb-89da-3aa6aadad97a.png)

**Comment by leocb** [comment] 2021-04-23 05:17
Duplicate of #30 see fix on that same issue

**Closed by leocb** 2021-04-23 05:17 UTC

**Comment by seikosantana** [comment] 2021-04-23 05:52
Thank you.
Anyway i also found out that setting `UseVisualStyleBackColor` property of the containing `TabPage` to `false` also fixes the issue.
